name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
